---
- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - unzip
    - unrar
    - mediainfo
    - curl
    - php5-fpm
    - php5-cli
    - php5-geoip
    - php5-curl
    - git-core
- name: create install directory
  file: path={{ rtorrent_rutorrent_install_path|dirname }} state=directory owner=www-data group=www-data
- name: download rutorrent
  git: >
    repo={{ rtorrent_rutorrent_repo }} dest={{ rtorrent_rutorrent_install_path }}
    version={{ rtorrent_rutorrent_version }} update=yes force=yes
  notify:
   - restart php5-fpm
   - restart rtorrent
- name: adjust rutorrent autotools plugin inteval
  lineinfile: >
    dest={{ rtorrent_rutorrent_install_path }}/plugins/autotools/conf.php
    regexp="^(\s*)\$autowatch_interval" line="\1$autowatch_interval = {{ rtorrent_rutorrent_autotools_interval }};"
    backrefs=yes state=present
  notify: restart rtorrent
- name: fix share directory ownership
  file: path={{ rtorrent_rutorrent_install_path }}/share owner=www-data group=www-data recurse=yes
