mastermind_group: mastermind

sabnzbd_download_dir: "{{ mastermind_download_dir }}/incomplete"
sabnzbd_complete_dir: "{{ mastermind_download_dir }}/usenet"
sabnzbd_script_dir: "{{ sickbeard_autoprocesstv_script_dir }}"
sabnzbd_web_color: gold
sabnzbd_permissions: 775
rtorrent_download_dir: "{{ mastermind_download_dir }}/torrents"
rtorrent_watch_dir: "{{ mastermind_download_dir }}/watch"
rtorrent_install_rutorrent: yes
rtorrent_install_rutorrent_plugins: yes
rtorrent_umask: "002"
rtorrent_service_enable: yes
rtorrent_rutorrent_autotools_interval: 15
sickbeard_web_root: /sickbeard
sickbeard_root_dir: "{{ mastermind_media_dir }}/tv"
sickbeard_tv_download_dir: "{{ mastermind_download_dir }}/tv"
sickbeard_process_automatically: 1
sickbeard_nzb_method: sabnzbd
sickbeard_sab_apikey: "{{ sabnzbd_api_key }}"
sickbeard_sab_host: http://{{ sabnzbd_host }}:{{ sabnzbd_port }}/
sickbeard_torrent_dir: "{{ rtorrent_watch_dir }}/tv"
sickbeard_use_plex: 1
sickbeard_plex_update_library: 1
sickbeard_plex_server_host: localhost:32400
couchpotato_url_base: /couchpotato
couchpotato_manage_enabled: 1
couchpotato_manage_library: "{{ mastermind_media_dir }}/movies"
couchpotato_renamer_enabled: 1
couchpotato_renamer_from: "{{ mastermind_download_dir }}/movies"
couchpotato_renamer_to: "{{ couchpotato_manage_library }}"
couchpotato_sabnzbd_enabled: 1
couchpotato_sabnzbd_host: "{{ sabnzbd_host }}:{{ sabnzbd_port }}"
couchpotato_sabnzbd_api_key: "{{ sabnzbd_api_key }}"
couchpotato_rtorrent_enabled: 1
couchpotato_rtorrent_host: "scgi://{{ rtorrent_scgi_host }}:{{ rtorrent_scgi_port }}"
couchpotato_rtorrent_remove_complete: 1
couchpotato_plex_enabled: 1
couchpotato_plex_media_server: localhost
couchpotato_renamer_file_name: "<original>.<ext>"
couchpotato_renamer_folder_name: "<thename> (<year>)"
couchpotato_renamer_unrar: 1
couchpotato_renamer_cleanup: 1
couchpotato_renamer_run_every: 1
couchpotato_renamer_force_every: 1
newrelic_install_nginx_plugin: yes
newrelic_nginx_plugin_status_name: mastermind
newrelic_nginx_plugin_status_url: http://localhost/nginx_stub_status
