---
- name: restart newrelic sysmon
  service: name={{ newrelic_service_name }} state=restarted
- name: restart newrelic nginx plugin
  service: name={{ newrelic_nginx_plugin_service_name }} state=restarted
