---
- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - python-passlib
- name: create {{ mastermind_group }} group
  group: name={{ mastermind_group }} system=yes state=present
- name: create directories
  file: path={{ item.path }} group={{ mastermind_group }} mode={{ item.mode|default("775") }} state=directory
  with_items:
    - path: "{{ mastermind_download_dir }}"
      mode: "755"
    - path: "{{ mastermind_media_dir }}"
      mode: "755"
    - path: "{{ sickbeard_tv_download_dir }}"
    - path: "{{ sickbeard_torrent_dir }}"
    - path: "{{ couchpotato_renamer_from }}"
- name: install nginx-extras
  apt: name=nginx-extras update_cache=yes state=latest
- name: delete default site symlink
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: install ssl key
  copy:
    content: "{{ mastermind_ssl_key }}"
    dest: "{{ mastermind_ssl_key_path }}"
    mode: 600
  notify: reload nginx
- name: install ssl certificate
  copy:
    content: "{{ mastermind_ssl_cert }}"
    dest: "{{ mastermind_ssl_cert_path }}"
    mode: 644
  notify: reload nginx
- name: setup htpasswd
  htpasswd: path=/etc/nginx/.htpasswd name={{ mastermind_user }} password={{ mastermind_password }}
            owner=root group=www-data mode=0640
- name: install mastermind site
  template: src=mastermind.nginx.j2 dest=/etc/nginx/sites-available/mastermind
  notify: reload nginx
- name: create mastermind site symlink
  file: src=/etc/nginx/sites-available/mastermind dest=/etc/nginx/sites-enabled/mastermind state=link
  notify: reload nginx
- name: add services to mastermind group
  user: name={{ item }} groups={{ mastermind_group }} append=yes
  with_items:
    - "{{ sickbeard_user }}"
    - "{{ couchpotato_user }}"
    - "{{ sabnzbd_user }}"
    - "{{ sonarr_user }}"
    - "{{ rtorrent_user }}"
  notify:
    - restart sickbeard
    - restart couchpotato
    - restart sabnzbdplus
    - restart sonarr
    - restart rtorrent
- name: add services to sabnzbd and rtorrent group
  user: name={{ item }} groups={{ sabnzbd_user }},{{ rtorrent_user }} append=yes
  with_items:
    - "{{ sickbeard_user }}"
    - "{{ sonarr_user }}"
    - "{{ couchpotato_user }}"
  notify:
    - restart sickbeard
    - restart couchpotato
    - restart sonarr
- name: add rtorrent to service groups
  user: name={{ rtorrent_user }} groups={{ item }} append=yes
  with_items:
    - "{{ sickbeard_user }}"
    - "{{ sonarr_user }}"
    - "{{ couchpotato_user }}"
  notify:
    - restart rtorrent
